= twinkly-kt
:doctype: article
:description: Project Documentation for twinkly-kt
:keywords: twinkly, kotlin
:icons: font
:toc:
:toc-title: Contents
:toclevels: 5

== About

This my attempt to bring control of twinkly devices to the kotlin world.

It is based on these projects:

- https://github.com/xled/xled-docs
- https://github.com/scrool/xled (Pavol Babinčák)
- https://github.com/Anders-Holst/xled_plus (Anders Holst)
- https://xled-docs.readthedocs.io/en/latest/rest_api.html

Also contained is a stripped down and kotlinized version of minim
by Damien Quartz which only supports line in currently.
The original implementation which was meant to be used within the
processing framework can be found here: https://github.com/ddf/Minim/tree/main

Involved is also some reverse engineering from the official twinkly android app.
But this turned out to be a waste of time as there are a lot of details lost in the decompilation process. F.e. the list of supported devices does not contain all products which are officially supported and work within the app (such as the Curtain 210 which I own).
Also a lot of code which is originally kotlin cannot be reversed to useful code a lot of ends up in outcommented assembler or signature descriptions.
So for now we have say big thanks to the people who have found so much.

Another mystery was the usage of playlists and movies. I was actually able to upload a new movie but it turned out that I just messed up an existing movie which was actually in my playlist.
Creating a new movie did not succeed even I got an expected answer from the api.

Because of that fact that I cannot get the movie features to work properly for me I insteaddo the same thing it seems all the others do - I use the realtime frame feature which utilizes the UDP protocoll to upload binary frame data to the device. This works really fast over WLAN and makes possible impressive framerates. Of course this approach has the downside that it depends on a WLAN connection and a player software. On the other hand this allows for a lot of fun stuff.

This project is far from feature complete, but I think it`s now good enough to see the light of the world :)

== Documentation

=== Known Endpoints

==== XLed Devices

Most of these endpoints are determined using the xled python module.

I currently have two twinkly curtain 210.
That device type does not appear in the lists found within the code of android app.
I am sure that some things are swallowed during the decompilation process as the device is definitely supported by that app.

Furthermore I want to note that it seems that devices which are connected into an area inside the app are behaving as one thing when using the api. F.e. if you switch the mode on one device which is part of an area all of the participating devices will switch off.
The only exception to that seems to be the saturation level which can be set separately for all the devices.

===== brightness
get + post

http://$host/xled/v1/led/out/brightness

===== color
get + post

http://$host/xled/v1/led/color

===== config
get

http://$host/xled/v1/led/config

===== deviceInfo
get

http://$host/xled/v1/gestalt

===== effects
get

http://$host/xled/v1/led/effects

===== effectsCurrent
get

http://$host/xled/v1/led/effects/current

===== layout
get

http://$host/xled/v1/led/layout/full

===== ledReset
return get("http://$host/xled/v1/led/reset")

===== login
post

http://$host/xled/v1/login

===== verify
post

http://$host/xled/v1/verify

===== mode
get + post

http://$host/xled/v1/led/mode

===== movie
post

http://$host/xled/v1/led/movie/full

===== movieConfig
get + post

http://$host/xled/v1/led/movie/config

===== movies
get

http://$host/xled/v1/movies

===== moviesCurrent
get

http://$host/xled/v1/movies/current

===== playlist
get

http://$host/xled/v1/playlist

===== playlistCurrent
get

http://$host/xled/v1/playlist/current

===== saturation
get + post

http://$host/xled/v1/led/out/saturation

==== XMusic Microphone

These endpoints differ from what I have found in the code of the android app.

===== musicConfig
get

http://$host/xmusic/v1/music/config

===== musicMode
get

http://$host/xmusic/v1/music/mode

===== musicMicEnabled
get

http://$host/xmusic/v1/music/mic_enabled

===== musicStats
get

http://$host/xmusic/v1/music/stats
