server:
  port: 8024

application:
  devices:
    - curtain1:
        ipAddress: 192.168.178.35
        deviceOrigin: TOP_LEFT
    - curtain2:
        ipAddress: 192.168.178.52
        deviceOrigin: TOP_LEFT
