package de.visualdigits.kotlin.klanglicht.model.lightmanager.json


class Device(
    val amazonmail: String? = null,
    val balogin: String? = null,
    val bapass: String? = null,
    val cloudlogin: String? = null,
    val cloudpwd: String? = null,
    val connectcloud: String? = null,
    val connectlocal: String? = null,
    val currentip: String? = null,
    val ddns: Boolean? = null,
    val dhcpoff: Boolean? = null,
    val dns: String? = null,
    val emailalm: String? = null,
    val emailfrom: String? = null,
    val emailstd: String? = null,
    val enoceanrelease: Boolean? = null,
    val firmware: String? = null,
    val gateway: String? = null,
    val googlemail: String? = null,
    val headch: Int? = null,
    val highmpfs: String? = null,
    val ip: String? = null,
    val latitude: String? = null,
    val ledoff: Boolean? = null,
    val logenabled: Boolean? = null,
    val logpass: String? = null,
    val longitude: String? = null,
    val manualip: String? = null,
    val mode433: Int? = null,
    val mode868: Int? = null,
    val nochannelcheck: Boolean? = null,
    val passphrase: String? = null,
    val smallbandwidth: Boolean? = null,
    val ssid: String? = null,
    val subnet: String? = null,
    val timezone: Int? = null,
    val wifiscan: Map<String, Long>? = null,
)
