package de.visualdigits.kotlin.klanglicht.model.lightmanager.json


class Settings(
    val currentfile: String? = null,
    val ext1ch: Int? = null,
    val ext2ch: Int? = null,
    val ext3ch: Int? = null,
    val ext4ch: Int? = null,
    val ext5ch: Int? = null,
    val ext6ch: Int? = null,
    val ext7ch: Int? = null,
    val ext8ch: Int? = null,
    val extmac1: String? = null,
    val extmac2: String? = null,
    val extmac3: String? = null,
    val extmac4: String? = null,
    val extmac5: String? = null,
    val extmac6: String? = null,
    val extmac7: String? = null,
    val extmac8: String? = null,
    val extname1: String? = null,
    val extname2: String? = null,
    val extname3: String? = null,
    val extname4: String? = null,
    val extname5: String? = null,
    val extname6: String? = null,
    val extname7: String? = null,
    val extname8: String? = null,
    val filename: String? = null,
    val lastactor: Int? = null,
    val marksameactor: Boolean? = null,
    val master: String? = null,
    val nukibridges: String? = null,
    val olympiaid: Int? = null,
    val studioversion: String? = null,
    val tmpoff0: Int? = null,
    val tmpoff1: Int? = null,
    val tmpoff10: Int? = null,
    val tmpoff11: Int? = null,
    val tmpoff2: Int? = null,
    val tmpoff3: Int? = null,
    val tmpoff4: Int? = null,
    val tmpoff5: Int? = null,
    val tmpoff6: Int? = null,
    val tmpoff7: Int? = null,
    val tmpoff8: Int? = null,
    val tmpoff9: Int? = null
)
