server:
  port: 8888
  application:
    name: Twinkly KT
  logging:
    requestLogging: false

spring:
  profiles:
    active: local
  config:
    import: file:${user.home}/.twinkly/resources/application.yml

