name: Twinkly API Kotlin

on:
  push:
    branches:
      - main
permissions:
  actions: write
jobs:
  build-and-deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build package
        run: mvn --batch-mode clean package -DskipTests

      - name: Publish snapshot
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        with:
          name: twinkly-kt
          path: |
            /home/runner/work/sknull/twinkly-kt/target/*.jar
            !/home/runner/work/sknull/twinkly-kt/target/*sources.jar
            !/home/runner/work/sknull/twinkly-kt/target/original*.jar
