name: Twinkly API Kotlin

on:
  push:
    branches:
      - main
permissions:
  contents: read
  issues: write
jobs:
  build-and-deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build package
        run: mvn --batch-mode clean package -DskipTests

      - name: Publish snapshot
        run: mvn deploy -DskipTests -Dregistry=https://maven.pkg.github.com/phanatic -Dtoken=GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
